### ISSUE TITLE
Missing poolboy-admin image

### ISSUE THREAD

**Issue by MAHDTech** [redhat-cop/poolboy#58]
Hi there,

While testing out Poolboy I noticed the [default](https://github.com/redhat-cop/poolboy/blob/b5c01915322c1fad8683920fa93c18473218e1d1/helm/values.yaml#L40) value for the Helm chart is to enable poolboy admin.

However it seems the image isn't available publicly at [quay.io/redhat-cop/poolboy-admin](https://quay.io/repository/redhat-cop/poolboy-admin?tag=latest&tab=tags)

Has the image been moved to a new path?

Thanks

**Comment by jkupferer** [comment]
Yes, sorry about that. The poolboy admin project started and then got moved to the back-burner. I am updating the helm chart to not deploy the admin ui by default. Hopefully we will be able to get back to it sometime later this year.
